config/routes.rb
Rails.application.routes.draw do
  root 'main#index', as: 'home'

  # get 'login' => 'main#login', as: 'login'


  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"

  resources :users, only: [:index, :edit, :update, :destroy, :new, :create, :show]
  resources :courses do
    resources :posts do
      resources :comments, only: [:create]
    end
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :body, presence: true, length: {minimum: 1}

end

app/models/course.rb
class Course < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :tasks, dependent: :destroy

  validates :name, presence: true, length: {minimum: 1}
  belongs_to :user
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
	attribute :user
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy

  belongs_to :course
  belongs_to :user

  validates :title, presence: true, length: {minimum: 1}
  validates :body, presence: true, length: {minimum: 1}


end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :course
  belongs_to :user

  validates :title, presence: true, length: {minimum: 1}
  validates :body, presence: true, length: {minimum: 10}
  validates :deadline, presence: true, length: {minimum: 8}

end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :courses
	has_many :posts
	has_many :tasks
	before_save :downcase_email
	# Асоціації
	belongs_to :admin, optional: true
	validates :name, presence: true, length: {minimum: 4}
	validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: true
	validates :password, presence: true, length: {minimum: 8}
	
	def downcase_email
		self.email = email.downcase
	end
 
 
	before_save :downcase_email
 
	validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: true
end
 

app/controllers/main_controller.rb
class MainController < ApplicationController
	before_action :redirect_if_not_authenticated, only: [:index]
	def index
		@courses = Course.all
	end

	def login
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :redirect_if_not_authenticated, only: [:create, :new, :index, :show, :destroy, :edit]
	def index
		redirect_to course_path
	end

	def new
		@post = Post.new
	end
	
	def show
		@post = Post.find(params[:id])
		@course = @post.course
		@comment = Comment.all
	end

	def edit
		@course = Course.find(params[:course_id])
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if(@post.update(post_params))
			course_id = @post.course_id
			redirect_to course_path(course_id)
		else
			render 'edit'
		end
	end

	def destroy 
		@post = Post.find(params[:id])
		course_id = @post.course_id
		@post.destroy
		redirect_to course_path(course_id)
	end
	 
	def create 
		course = Course.find(params[:course_id])
		@post = course.posts.new(post_params)
		@post.user = current_user
		if(@post.save)
			redirect_to course_path(course)
		else
			render 'new'
		end
	end
	
	private def post_params
		params.require(:post).permit(:title, :body, :date)
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :redirect_if_not_authenticated, only: [:create, :new, :index, :show, :destroy, :edit]
	def index
		redirect_to course_path	
	end

	def new
		@task = Task.new
	end
	def show
		@task = Task.find(params[:id])
		@course = @task.course
	end

	def edit
		@course = Course.find(params[:course_id])
  		@task = Task.find(params[:id])
	end

	def update
		@course = Course.find(params[:course_id])
		@task = @course.tasks.find(params[:id])
		if @task.update(task_params)
		  redirect_to course_task_path(@course, @task)
		else
		  render 'edit'
		end
	end
	 

	def destroy 
		@task = Task.find(params[:id])
		@course = Course.find(params[:course_id])
		@task.destroy
		redirect_to @course
	end

	def create 
		course = Course.find(params[:course_id])
		@task = course.tasks.new(task_params)
		@task.user = current_user
		@task.date_of_published = DateTime.now
		if(@task.save)
			redirect_to course_path(course)
		else
			render 'new'
		end
	end
	private def task_params
		params.require(:task).permit(:title, :body, :deadline)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Platform</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" %>
    <style>
      body {
        margin: 0;
        padding: 0;
        overflow-x: hidden;
        width: 100%;
        max-width: 1920px;
        min-height: 100vh;
        background-blend-mode: multiply;
        background-image: linear-gradient(rgba(0, 0, 0, 0.3333333333), rgba(0, 0, 0, 0.3333333333)), url(https://www.uzhnu.edu.ua/uploads/news/20180903_1006_03_den_znan_afisha.jpg);
        background-position: center center;
        background-size: cover;
        background-attachment: fixed;
        overflow-x: hidden;
        color: #fff;
      }

      a {
        text-decoration: none;
        color: inherit;
      }

      img {
        max-width: 100%;
        height: auto;
      }

      h1,
      h2,
      h3,
      h4,
      h5,
      h6 {
        margin: 0;
        padding: 0;
      }

      ul,
      li,
      ol {
        list-style: none;
      }

      .btn {
        background-color: #fff;
        color: #000;
      }

      .form-control {
        margin: 10px 0;
      }

      .com__ava{
        width: 40px; 
        height: 40px; 
        border-radius: 50%; 
        overflow: hidden;
        flex: 0 0 auto;
      }

      .com__ava img{
        width: 100%; 
        height: 100%; 
        object-fit:cover;
      }

      .new_comment{
        display: flex;
        max-width: 95%;
        justify-content: space-between;
      }
      .card_image img{
        width: 100%;
        height: 100%;
        object-fit: cover;
      }
    </style>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="header">
        <div class="container" style="padding: 0 25px">
            <div class="header_logo_site">
                <div class="img">
                  <%= link_to home_path do %>
                     <%= image_tag('logo.png')  %>
                  <% end %>
                </div>
                <div class="name_logo">Сайт електронного навчання</div>
            </div>
            <% if current_user %>
            <div class="menu">
                <div class="menu_show">
                    <span class="user_name"><%= current_user.name %></span>
                <div class="menu_user_logo">
                    <%= image_tag('user.png') %>
                </div>
                </div>
                <ul class="navbar">
                    <li>
                      <%= link_to "Всі курси", home_path %>
                    </li>
                    <% if current_user.role == "admin" %>
                      <li>
                        <%= link_to "Всі користувачі", users_path %>
                      <li>
                    <% end %>
                    <li>
                      <%= link_to "Профіль", user_path(current_user.id) %>
                    </li>
                    <div class="hr"></div>
                    <li><%= link_to "Вийти з акаунту", logout_path %></li>
                </ul>
            </div>
            <% end %>
        </div>
    </header>
    <div class="section">
      <div class="container">
       <%= yield %>
      </div>
    <div> 
    <footer class="footer"></footer>
    <script>
      const body = document.body;
      const iconMenu = document.querySelector('.menu_user_logo');
      const bodyMenu = document.querySelector('.navbar');
      if (iconMenu) {
          iconMenu.addEventListener("click", function (e) {
              iconMenu.classList.toggle('_active');
              bodyMenu.classList.toggle('_active');
          })
      }

      const newsButton = document.querySelector('#newsButton');
      const tasksButton = document.querySelector('#tasksButton');
      const newsContent = document.querySelector('#newsContent');
      const tasksContent = document.querySelector('#tasksContent');

      newsButton.addEventListener('click', function() {
          newsContent.style.display = 'block';
          tasksContent.style.display = 'none';
      });

      tasksButton.addEventListener('click', function() {
          newsContent.style.display = 'none';
          tasksContent.style.display = 'block';
      });




      const activeLine = document.querySelector('.active-line');

      newsButton.addEventListener('click', function() {
        newsButton.classList.add('active');
        tasksButton.classList.remove('active');
        newsContent.classList.add('active');
        tasksContent.classList.remove('active');
        activeLine.style.left = '0';
      });

      tasksButton.addEventListener('click', function() {
        newsButton.classList.remove('active');
        tasksButton.classList.add('active');
        newsContent.classList.remove('active');
        tasksContent.classList.add('active');
        activeLine.style.left = '50%';
      });



      const taskHeaders = document.querySelectorAll('.task_header');
      const taskBodies = document.querySelectorAll('.task_body');
      const taskFooters = document.querySelectorAll('.task_footer');


      taskHeaders.forEach(function(taskHeader, index) {
        taskHeader.addEventListener('click', function() {
          
          const isTaskBodyVisible = taskBodies[index].style.display === 'block';

          
          if (isTaskBodyVisible) {
            taskBodies[index].style.display = 'none';
            taskFooters[index].style.display = 'none';
          } else {
            taskBodies[index].style.display = 'block';
            taskFooters[index].style.display = 'block';
          }
        });
      });
    </script>  
  </body>
</html>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>